name: Backend and Frontend Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment for backend
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install backend dependencies
      - name: Install backend dependencies
        run: |
          npm install

      # Step 4: Run backend tests
      - name: Run Backend Tests
        run: npm test

  frontend-test:
    runs-on: ubuntu-latest
    needs: backend-test  # Run frontend tests only if backend tests pass
    if: success()  # Ensure frontend tests only run when backend tests are successful

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Step 4: Run frontend tests using react-scripts
      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test -- --ci --runInBand --reporters=default --reporters=jest-junit

  # Optional: Add linting tasks for both backend and frontend
  backend-lint:
    runs-on: ubuntu-latest
    needs: backend-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for linting
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Lint on Backend
        run: npm run lint

  frontend-lint:
    runs-on: ubuntu-latest
    needs: frontend-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for linting
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run Lint on Frontend
        run: |
          cd frontend
          npm run lint
