name: Backend and Frontend Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Backend Dependencies
        run: npm install

      - name: Run Backend Tests
        run: npm test

  frontend-test:
    runs-on: ubuntu-latest
    needs: backend-test
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test -- --ci --runInBand --reporters=default --reporters=jest-junit
